import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>

      <Head>
        <title>NEXTJS.ORG CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <nav>


      <ul>

        <li><Image src="/logo.png" height={20} width={130} alt="Logo" /></li>

        <li>
          <a href="#">Showcase</a>
        </li>
        
        <li>
          <a href="#">Docs</a>
        </li>

        <li>
          <a href="#">Blog</a>
        </li>

        <li>
          <a href="#">Analytics</a>
        </li>

        <li>
          <a href="#">Examples</a>
        </li>

        <li>
          <a href="#">Enterprise</a>
        </li>

        <li>
          <a class="feedback" href="#">Feedback</a>
        </li>
      </ul>

    </nav>

    <h1 id='header'>The React Framework
for Production</h1>

    <h3 id="header">Next.js gives you the best developer experience with all the features you need for production: hybrid static & server rendering, TypeScript support, smart bundling, route pre-fetching, and more. No config needed.</h3>

      
    <div id="buttons">
      <button class="blue">Start Learning</button>
      <button>Documentation</button>
    </div>

    <h3>THE WEB SDK</h3>
    <h4>Next.js has all the tools you need to make the Web. Faster.</h4>

    <div id="cardcontainer">

      <div id="card1">
        <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card2">
        <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card3">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card4">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card5">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card6">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card7">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card8">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

      <div id="card9">
      <h1>Image Optimization</h1>
        <h2>Image Component and Image Optimization</h2>
        <a href='#'>Documentation</a>
      </div>

    </div>

    
    <h3>Learn Next Js</h3>
    <h4>Learn Next.js step-by-step and earn points</h4>

    <Image src="/screenshot.avif" height={600} width={900} />

    <button class="blue">Get Started</button>

    <div id="form">
      <div id="left">
        <h1>Next.js is getting better every day — don’t miss out on all the action.</h1>
        <h4>Join the Next.js newsletter and stay updated on new releases and features, guides, and case studies.</h4>
      </div>
      <div id="right">
        <input placeholder='you@domain.com' />
        <button class="black">Subscribe</button>
      </div>
    </div>

    <div id="footer">

    <div id='first'>
      <ul>
        <h1>General Resources</h1>
        <li>Docs</li>
        <li>Learn</li>
        <li>Showcase</li>
        <li>Blogs</li>
        <li>Analytics</li>
        <li>Enterprise</li>
      </ul>
    </div>

    <div id='second'>
      <ul>
        <h1>More</h1>
        <li>Docs</li>
        <li>Learn</li>
        <li>Showcase</li>
        <li>Blogs</li>
        <li>Analytics</li>
        <li>Enterprise</li>
      </ul>
    </div>

    <div id='third'>
      <ul>
        <h1>About Vercel</h1>
        <li>Docs</li>
        <li>Learn</li>
        <li>Showcase</li>
        <li>Blogs</li>
        <li>Analytics</li>
        <li>Enterprise</li>
      </ul>
    </div>

    <div id='forth'>
      <ul>
        <h1>Legal</h1>
        <li>Docs</li>
        <li>Learn</li>
        <li>Showcase</li>
        <li>Blogs</li>
        <li>Analytics</li>
        <li>Enterprise</li>
      </ul>
    </div>




    </div>


    <h5 class="copyright">Copyright. 2022 Vercel, Inc. All Rights Reserved</h5>

    </div>
  )
}
